language: php

php:
  - 5.5

before_script:
  - composer install

script: phpunit --configuration=phpunit.full.xml --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
